services:
  fuseki:
    image: stain/jena-fuseki:5.1.0
    container_name: qlgp_fuseki
    ports:
    - 3030:3030
    volumes:
    - ./fuseki/config.ttl:/fuseki/config.ttl
    - ./fuseki/rules:/fuseki/rules
    environment:
    - FUSEKI_ARGS=--config /fuseki/config.ttl
    - ADMIN_PASSWORD=1
    restart: unless-stopped
    