services:
  database:
    build:
      dockerfile_inline: |
        FROM mysql:8.4
        COPY ./init.sql /docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: mysqladmin ping --silent
  backend:
    build:
      dockerfile_inline: |
        FROM node:alpine
        WORKDIR /app
        COPY ./package.json .
        RUN npm install
        COPY . .
        CMD ["npm", "start"]
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - HOST_NAME=database
      - Database=QLGP
      - User=root
      - Password=root
    depends_on:
      database:
        condition: service_healthy

